function fileHandler_html4(l,f){if("upload"==KUPLOADTOP.G_CURRKUPLOADER._config.mode){var g=KUPLOADTOP.G_CURRKUPLOADER._config.maxTotalFileCount,a=!0,c=[],m={file:l,name:getFileName(f,!1),size:"",type:"",lastModifiedDate:""};c.push(m);var m=[],e=KUPLOADTOP.G_CURRKUPLOADER.frameWin.getTotalFileCount(),h=KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.duplication,d=0,p=!1;"0"==KUPLOADTOP.G_CURRKUPLOADER._config.allowDuplicationFile&&(p=sameFileCheck(c[0]));if(p)"0"==h&&alert(c[0].name+" "+RAONKUpload_Lang.message_duplication_file);
else{var h=!1,p=KUPLOADTOP.G_CURRKUPLOADER._config.extension,t=p.extArr.length;if(0<t){var u=p.allowOrLimit;if("1"==u){for(var q=getExtension(c[0].name),n=0;n<t;n++)if(("***"==p.extArr[n]?"":p.extArr[n])==q){h=!0;break}h||m.push(""==q?'" "':q)}else for(q=getExtension(c[0].name),n=0;n<t;n++)if(("***"==p.extArr[n]?"":p.extArr[n])==q){h=!1;m.push(""==q?'" "':q);break}else h=!0}else h=!0;calcTotalSize();p=TOTALREALFILENUM;if(0!=g&&p+1>g){alert(RAONKUpload_Lang.file_maximum+" "+g+RAONKUpload_Lang.message_limit_num);
return}if(h){var v=g="";document.getElementById("tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID)&&(v=document.getElementById("tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).value);null==f&&(f="");(g=f)&&(g=KUPLOADTOP.RAONKUPLOAD.util.trim(g));if("undefined"==typeof g||null==g)g="undefined"==typeof filePathSplit[0]||null==filePathSplit[0]?"":filePathSplit[0].substring(0,filePathSplit[0].lastIndexOf(KUPLOADTOP.RAONKUPLOAD.UserAgent.osSeparator)+1)+c[0].name;if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useAddEvent)try{var k=
c[0].file,b={strName:c[0].name,nSize:c[0].size,nIndex:e+d,strPath:g,dropZoneId:"",objFile:k},a=KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_BeforeAddFile(KUPLOADTOP.G_CURRKUPLOADER.ID,b);!1!==a&&(a=!0)}catch(w){}if(a){a=c[0].type;if(null==a||void 0==a||""==a)a="application/octet-stream";a={file:c[0].file,guid:"",fileIdx:"",webPath:"",originName:c[0].name,fileSize:c[0].size,uploadName:"",uploadPath:"",logicalPath:"",status:"ready",fileExt:"",isDelete:"n",isWebFile:"n",localPath:g,customValue:"",responseCustomValue:"",
headerEx:"",lastModifiedDate:c[0].lastModifiedDate,mimeType:a};RESULTFILELIST.push(a);a.isFolder="0";addFileList(a);if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useAfterAddEvent)try{calcTotalSize(),k=c[0].file,b={strName:c[0].name,nSize:c[0].size,nIndex:e+d,strPath:a.localPath,dropZoneId:"",objFile:k},KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_AfterAddFile(KUPLOADTOP.G_CURRKUPLOADER.ID,b)}catch(x){}d++;c=document.getElementById("files_container");KUPLOADTOP.G_CURRKUPLOADER.TagID=KUPLOADTOP.RAONKUPLOAD.util.makeGuidTagName();
k=document.createElement("form");k.setAttribute("id","form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);k.setAttribute("method","post");k.setAttribute("enctype","multipart/form-data");k.setAttribute("encoding","multipart/form-data");b=document.createElement("span");b.className="input_image_add";b.innerHTML=RAONKUpload_Lang.btn_add;""!=KUPLOADTOP.G_CURRKUPLOADER._config.customHeaderColor&&(b.style.background=KUPLOADTOP.G_CURRKUPLOADER._config.customHeaderColor);""!=KUPLOADTOP.G_CURRKUPLOADER._config.customFooterColor&&
(b.style.color=KUPLOADTOP.G_CURRKUPLOADER._config.customFooterColor);var r=document.createElement("input");r.setAttribute("id","file_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);r.setAttribute("name","file_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);r.setAttribute("type","file");KUPLOADTOP.RAONKUPLOAD.util.addEvent(r,"change",function(){fileHandler_html4(r,r.value)});KUPLOADTOP.RAONKUPLOAD.util.addEvent(r,"blur",function(){focusHandler(r)});e=document.createElement("input");e.setAttribute("id","tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);
e.setAttribute("name","tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);e.setAttribute("type","hidden");e.setAttribute("value","0");k.appendChild(b);k.appendChild(r);k.appendChild(e);b=document.createElement("div");b.appendChild(k);c.appendChild(b);b.previousSibling&&(b.previousSibling.style.display="none",b.previousSibling.childNodes[0].childNodes[1].tabIndex="-1")}}}displayTotalSizeAndNum();c=m.length;if(0<c){b="";k=KUPLOADTOP.G_CURRKUPLOADER._config.extension.extArr;b=k.length;for(e=0;e<b;e++)"***"==k[e]&&
(k[e]='" "');"1"==u?1<c?(b=RAONKUpload_Lang.message_not_allow_exts,b=b.replace("{0}",c),b=b.replace("{1}",k)):(b=m[0]+" "+RAONKUpload_Lang.message_not_allow_ext,b=b.replace("{0}",k)):1<c?(b=RAONKUpload_Lang.message_not_limit_exts,b=b.replace("{0}",c),b=b.replace("{1}",k)):(b=m[0]+" "+RAONKUpload_Lang.message_not_limit_ext,b=b.replace("{0}",k));alert(b)}"1"==KUPLOADTOP.G_CURRKUPLOADER._config.use_file_sort&&"1"==KUPLOADTOP.G_CURRKUPLOADER._config.auto_sort&&"1"!=KUPLOADTOP.G_CURRKUPLOADER._config.sort_field&&
sortTotalFileList(KUPLOADTOP.G_CURRKUPLOADER._config.sort_field,KUPLOADTOP.G_CURRKUPLOADER._config.sort_ascdesc);calcTotalSize();fileListSortIconReset();setFileListBorder();setTabOrder();setListvalue();setLargeFileAllList();1==v&&(document.getElementById("file_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).focus(),document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundImage="url("+KUPLOADTOP.G_CURRKUPLOADER._config.webPath.image+"img_bt_line.png)",document.getElementById("form_"+
KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundRepeat="no-repeat",document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundPositionY="2px",document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundPositionX="1px",document.getElementById("tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).value="1",G_FileHandlerControl=0);"thumbs"==KUPLOADTOP.G_CURRKUPLOADER._config.views&&thumbsViewWithCanvas();if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useAfterAddEndTimeEvent&&
0<d)try{KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_AfterAddAllFile(KUPLOADTOP.G_CURRKUPLOADER.ID)}catch(y){}}}
function processUploadHtml4(){if(!KUPLOADTOP.G_CURRKUPLOADER._config.uploadCancel){var l=getDialogDocument();0==upload_complete_count&&(G_UploadStartTime=(new Date).getTime()/1E3);var f=document.getElementById("files_container").getElementsByTagName("form"),g=0;if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.skipSentFile)for(var a=0;a<uploaders[upload_complete_count];a++)RESULTFILELIST[a].file&&"complete"==RESULTFILELIST[a].status&&g++;f=f[upload_complete_count+g];g=document.charset;document.charset="utf-8";
var c=upload_complete_count.toString();c==(uploaders.length-1).toString()&&(c+="z");RESULTFILELIST[uploaders[upload_complete_count]].guid=KUPLOADTOP.RAONKUPLOAD.util.makeGuid();var m=f.getElementsByTagName("input"),e=m[0],m=m[1];f.removeChild(m);for(var h=0,d=RESULTFILELIST.length,a=0;a<uploaders[upload_complete_count];a++)"n"==RESULTFILELIST[a].isDelete&&(h+=parseInt(RESULTFILELIST[a].fileSize,10));for(a=uploaders[upload_complete_count]+1;a<d;a++)"y"==RESULTFILELIST[a].isWebFile&&(h+=parseInt(RESULTFILELIST[a].fileSize,
10));d=""+("kc"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"c02"+KUPLOADTOP.RAONKSolution.Agent.vertical);d+="k01"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k12"+KUPLOADTOP.RAONKSolution.Agent.formfeed+RESULTFILELIST[uploaders[upload_complete_count]].guid+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k14"+KUPLOADTOP.RAONKSolution.Agent.formfeed+RESULTFILELIST[uploaders[upload_complete_count]].originName+
KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k15"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.fileNameRule+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k16"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.fileNameRuleEx+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k17"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.folderNameRule+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k20"+KUPLOADTOP.RAONKSolution.Agent.formfeed+
c+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k21"+KUPLOADTOP.RAONKSolution.Agent.formfeed+RESULTFILELIST[uploaders[upload_complete_count]].customValue+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k22"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"1"+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k23"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"1"+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k24"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.allowedZeroFileSize+KUPLOADTOP.RAONKSolution.Agent.vertical;
"1"==KUPLOADTOP.G_CURRKUPLOADER._config.security.fileExtensionDetector&&(d+="k29"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"1"+KUPLOADTOP.RAONKSolution.Agent.vertical);var p=KUPLOADTOP.G_CURRKUPLOADER._config.maxOneFileSize;0!=p&&(d+="k40"+KUPLOADTOP.RAONKSolution.Agent.formfeed+p+KUPLOADTOP.RAONKSolution.Agent.vertical);var t=KUPLOADTOP.G_CURRKUPLOADER._config.maxTotalFileSize;0!=t&&(d+="k41"+KUPLOADTOP.RAONKSolution.Agent.formfeed+t+KUPLOADTOP.RAONKSolution.Agent.vertical,d+="k42"+KUPLOADTOP.RAONKSolution.Agent.formfeed+
h+KUPLOADTOP.RAONKSolution.Agent.vertical);a=document.createElement("input");a.type="hidden";c=KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(d);a.name=c.name;a.value=c.value;f.insertBefore(a,e);h=G_FormData.length;c=[];for(d=0;d<h;d++){var u=G_FormData[d].form_value,u="1"<=KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam?KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(u).value:encodeURIComponent(u),q=document.createElement("input");q.type="hidden";q.name=G_FormData[d].form_name;q.value=
u;f.insertBefore(q,e);c.push(q)}var n=document.createElement("div"),d=KUPLOADTOP.RAONKUPLOAD.util.getDefaultIframeSrc();n.innerHTML='<iframe name="uploadframe" id="uploadframe" style="display:none;" src="'+d+'"></iframe>';n.style.display="none";document.body.appendChild(n);KUPLOADTOP.RAONKUPLOAD.util.addEvent(n.firstChild,"load",function(){n.firstChild.contentWindow.postMessage("check","*")},!0);var v=function(b,a){var d=getUploadedFileListObj();try{d={strType:"upload",strCode:b,strMessage:a,arrUploadedFileList:d},
"function"!==typeof KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_OnError&&alert("Error Code : "+b+"\nError Message : "+a),KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_OnError(KUPLOADTOP.G_CURRKUPLOADER.ID,d)}catch(c){}if(1==G_MultiTranferCheck)G_MultiTranferCheck=4;else try{"0"==KUPLOADTOP.G_CURRKUPLOADER._config.skipSentFile&&fileListReset()}catch(e){}clearInterval(G_IntervalObj);PREVIOUSUPLOADEDSIZE=0;l.getElementById("RAON_K_UP_upload_size").innerHTML="-";clearInterval(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval);
KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=null;KUPLOADTOP.G_CURRKUPLOADER.processTime=0;0<getSessionKeepData(KUPLOADTOP.G_CURRKUPLOADER).length&&(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=!1);displayCommonReady(!1,KUPLOADTOP.G_CURRKUPLOADER);closeSendDialog();KUPLOADTOP.G_CURRKUPLOADER.cancel()};if(window.postMessage){var k=function(b){document.body.removeChild(n);KUPLOADTOP.RAONKUPLOAD.util.removeEvent(window,"message",k);b=KUPLOADTOP.RAONKUPLOAD.util.trim(b.data);b=KUPLOADTOP.RAONKUPLOAD.util.parseDataFromServer(b);
if(0==b.indexOf("[OK]"))if(b=b.replace("[OK]",""),b=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(b),"C012|response data decrypt error"==b)b=b.split("|"),v(b[0],b[1]);else{b=b.split(KUPLOADTOP.RAONKSolution.Agent.formfeed);var a=b[0],d="",c="",e=a.indexOf("::");-1<e&&(d=a.substring(0,e),a=a.substring(e+2,a.length));e=a.indexOf(":");-1<e&&(c=a.substring(0,e),a=a.substring(e+1,a.length));e="";e=a.length;"|"==a.substring(e-1,e)?(a=a.substring(0,e-1),e=getFileName(a,!1),a=a.substring(0,a.lastIndexOf("/"+
e))):e=getFileName(a,!1);RESULTFILELIST[uploaders[upload_complete_count]].uploadName=e;RESULTFILELIST[uploaders[upload_complete_count]].uploadPath=a;RESULTFILELIST[uploaders[upload_complete_count]].fileSize=b[2];RESULTFILELIST[uploaders[upload_complete_count]].status="complete";RESULTFILELIST[uploaders[upload_complete_count]].logicalPath="";RESULTFILELIST[uploaders[upload_complete_count]].responseCustomValue=b[1];""!=c&&(RESULTFILELIST[uploaders[upload_complete_count]].originName=c);RESULTFILELIST[uploaders[upload_complete_count]].hashValue=
d;KUPLOADTOP.G_CURRKUPLOADER.uploadedTaskId="";KUPLOADTOP.G_CURRKUPLOADER.uploadedSize=0;PREVIOUSUPLOADEDSIZE+=parseInt(b[2],10);clearInterval(G_IntervalObj);uploadProgressComplete_html4(KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(b[2]));upload_complete_count++;if(KUPLOADTOP.G_CURRKUPLOADER._config.uploadCancel){if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useUploadingCancelEvent){b={bAutoTransferFlag:!1,arrUploadedFileList:getUploadedFileListObj()};try{KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_UploadingCancel(KUPLOADTOP.G_CURRKUPLOADER.ID,
b)}catch(f){}}if(1==G_MultiTranferCheck)G_MultiTranferCheck=3;else try{"0"==KUPLOADTOP.G_CURRKUPLOADER._config.skipSentFile&&fileListReset()}catch(g){}PREVIOUSUPLOADEDSIZE=0;l.getElementById("RAON_K_UP_upload_size").innerHTML="-";clearInterval(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval);KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=null;KUPLOADTOP.G_CURRKUPLOADER.processTime=0;0<getSessionKeepData(KUPLOADTOP.G_CURRKUPLOADER).length&&(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=
!1);displayCommonReady(!1,KUPLOADTOP.G_CURRKUPLOADER);closeSendDialog();KUPLOADTOP.G_CURRKUPLOADER.cancel()}else upload_complete_count==TOTALUPLOADNUM?(PREVIOUSUPLOADEDSIZE=0,l.getElementById("RAON_K_UP_upload_size").innerHTML="-",totalUploadComplete(),0<getSessionKeepData(KUPLOADTOP.G_CURRKUPLOADER).length&&(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=!1)):(b=uploaders.indexOf(uploaders[upload_complete_count]),adjustUploadFileListScroll(b,upload_complete_count,TOTALUPLOADNUM),processUploadHtml4())}else if(0==
b.indexOf("[FAIL]")){b=b.replace("[FAIL]","");b=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(b);b=KUPLOADTOP.RAONKUPLOAD.util.getCodeAndMessage(b);a="";"020"==b.code?(a=RAONKUpload_Lang.message_limit_one_size,a=a.replace("{0}",KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(p).toString)):a="021"==b.code?RAONKUpload_Lang.message_file_ext_detect_html4:"022"==b.code?RAONKUpload_Lang.file_maximum+" "+KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(t).toString+RAONKUpload_Lang.message_limit_size:b.message;d=
0;if("020"==b.code||"021"==b.code||"022"==b.code){for(c=0;c<uploaders[upload_complete_count];c++)"y"==RESULTFILELIST[c].isDelete&&d++;var h=uploaders[upload_complete_count]-d;setSelectFile(h,0);h=KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm;KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=1;KUPLOADTOP.RAONKUPLOAD.DeleteSelectedFile(KUPLOADTOP.G_CURRKUPLOADER.ID);KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=h}if("022"==
b.code)for(e=RESULTFILELIST.length,c=uploaders[upload_complete_count];c<e;c++)"y"==RESULTFILELIST[c].isDelete?d++:"n"==RESULTFILELIST[c].isWebFile&&(h=c-d,setSelectFile(h,0),h=KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm,KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=1,KUPLOADTOP.RAONKUPLOAD.DeleteSelectedFile(KUPLOADTOP.G_CURRKUPLOADER.ID),KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=h,c--,e--);v(b.code,a)}};
KUPLOADTOP.RAONKUPLOAD.util.addEvent(window,"message",k)}f.setAttribute("target","uploadframe");f.setAttribute("action",KUPLOADTOP.G_CURRKUPLOADER._config.handlerUrl);l.getElementById("RAON_K_UP_current_upload_file_name").innerHTML=" "+RESULTFILELIST[uploaders[upload_complete_count]].originName;f.submit();document.charset=g;f.removeChild(a);for(a=h-1;0<=a;a--)f.removeChild(c[a]);f.insertBefore(m,e.nextSibling);uploadProgress_html4(upload_complete_count,TOTALUPLOADNUM,50)}}
function uploadProgress_html4(l,f,g){var a=getDialogDocument();adjustUploadFileListScroll(l-1,l,f);a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[l]).style.width="0%";G_IntervalObj=setInterval(function(){c()},400);var c=function(){var e;e=0;if(a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[l])){e=a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[l]).style.width.split("%");e=Math.round(1*e[0]*g/100);e++;if(e==parseInt(3*g/5,10)+1)m("1");else if(e==parseInt(4*g/5,10)+
1)m("2");else if(e==parseInt(9*g/10,10)+1)m("3");else if(e==parseInt(24*g/25,10)+1){m("4");return}if(1==e)if(a.getElementById("RAON_K_UP_upload_count"))a.getElementById("RAON_K_UP_upload_count").innerHTML=l+1+"/"+f;else return;var c=parseInt(1/g*100*e,10);a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[l])&&(a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[l]).style.width=c+"%",a.getElementById("RAON_K_UP_current_upload_progress_bar")&&(a.getElementById("RAON_K_UP_current_upload_progress_bar").style.width=
c+"%"),e=parseInt(1*l/f*100,10)+parseInt(parseInt(1/g*100*e,10)/f,10),a.getElementById("RAON_K_UP_total_upload_percent")&&(a.getElementById("RAON_K_UP_total_upload_percent").innerHTML=e+"%",a.getElementById("RAON_K_UP_total_upload_progress_bar")&&(a.getElementById("RAON_K_UP_total_upload_progress_bar").style.width=e+"%",a.getElementById("RAON_K_UP_upload_size")&&0==PREVIOUSUPLOADEDSIZE&&(a.getElementById("RAON_K_UP_upload_size").innerHTML="-"))))}},m=function(a){"1"==a?(clearInterval(G_IntervalObj),
G_IntervalObj=setInterval(function(){c()},800)):"2"==a?(clearInterval(G_IntervalObj),G_IntervalObj=setInterval(function(){c()},1E3)):"3"==a?(clearInterval(G_IntervalObj),G_IntervalObj=setInterval(function(){c()},1200)):"4"==a&&clearInterval(G_IntervalObj)};null==KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval&&(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=setInterval(function(){a.getElementById("RAON_K_UP_process_time").innerHTML=viewTime(++KUPLOADTOP.G_CURRKUPLOADER.processTime)},1E3))}
function uploadProgressComplete_html4(l){var f=getDialogDocument(),g=uploaders[upload_complete_count];if(void 0!=g){var a=parseInt(1*(g+1)/TOTALUPLOADNUM*100,10);f.getElementById("RAON_K_UP_current_upload_progress_bar").style.width="100%";f.getElementById("RAON_K_UP_uploadFileProgress_"+g).style.width="100%";f.getElementById("RAON_K_UP_uploadFilePercent_"+g).style.color="";f.getElementById("RAON_K_UP_uploadFilePercent_"+g).innerHTML="100%";f.getElementById("RAON_K_UP_uploadFileSize_"+g).innerHTML=
l.toString;UPLOADIDX++;f.getElementById("RAON_K_UP_upload_count").innerHTML=upload_complete_count+1+"/"+TOTALUPLOADNUM;f.getElementById("RAON_K_UP_total_upload_percent").innerHTML=a+"%";f.getElementById("RAON_K_UP_total_upload_progress_bar").style.width=a+"%";f.getElementById("RAON_K_UP_upload_size").innerHTML=KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(PREVIOUSUPLOADEDSIZE).toString;100==a&&(clearInterval(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval),KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=
null,KUPLOADTOP.G_CURRKUPLOADER.processTime=0)}};
